# Generated by Django 3.2.6 on 2021-09-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registerform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Your_Name', models.CharField(max_length=30)),
                ('Phone_Number', models.IntegerField()),
                ('Enter_Your_Father_Name', models.CharField(max_length=30)),
                ('Father_Phone_No', models.IntegerField()),
                ('Permanent_Address', models.CharField(max_length=100)),
                ('Select_Student_or_Employee', models.CharField(blank=True, choices=[('Student', 'Student'), ('Employee', 'Employee')], max_length=30, null=True)),
                ('Enter_Name_of_Your_Organization', models.CharField(max_length=100)),
                ('Emergency_Contact_Per', models.CharField(blank=True, choices=[('Relative', 'Relative'), ('Friend', 'Friend')], max_length=30, null=True)),
                ('Enter_their_name', models.CharField(max_length=30)),
                ('Contact_No', models.IntegerField()),
                ('Choose_Room_No', models.CharField(blank=True, choices=[('Room No.1', 'Room No.1'), ('Room No.2', 'Room No.2'), ('Room No.3', 'Room No.3'), ('Room No.4', 'Room No.4'), ('Room No.5', 'Room No.5')], max_length=30, null=True)),
                ('Date_Of_Joining', models.DateField()),
                ('Rent_Amount_Paid', models.IntegerField()),
            ],
        ),
    ]
